import argparse
import enum


class Argument(enum.Enum):
    ADDRESS = 'address'
    LOG_LEVEL = 'log-level'
    TWILIO_ACCOUNT_SID = 'twilio-account-sid'
    TWILIO_AUTH_TOKEN = 'twilio-auth-token'
    TWILIO_FROM_NUMBER = 'twilio-from-number'
    SMS_TO_NUMBER = 'sms-to-number'
    TRANSACTIONS_CHECK_INTERVAL = 'transactions-check-interval'
    SMS_TRANSACTION_DATE_FORMAT = 'sms-transaction-date-format'
    LOG_FORMAT = 'log-format'
    SMS_ENABLE = 'sms-enable'
    WEBHOOK_ENABLE = 'webhook-enable'
    VIBER_BOT_ENABLE = 'viber-bot-enable'
    WEBHOOK_URL = 'webhook-url'
    WEBHOOK_SECRET_KEY = 'webhook-secret-key'
    WEBHOOK_TRANSACTION_DATE_FORMAT = 'webhook-transaction-date-format'
    VIBER_BOT_NAME = 'viber-bot-name'
    VIBER_BOT_AVATAR = 'viber-bot-avatar'
    VIBER_BOT_TOKEN = 'viber-bot-token'
    VIBER_USER = 'viber-user'
    VIBER_BOT_TRANSACTION_DATE_FORMAT = 'viber-bot-transaction-date-format'
    VERSION = 'v'


arguments = {
    Argument.ADDRESS.value: {
        'type': str,
        'help': 'Hydra address',
        'required': True
    },
    Argument.LOG_LEVEL.value: {
        'type': str,
        'help': 'Level of logging',
        'choices': ['NOTSET', 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'],
        'default': 'INFO'
    },
    Argument.TWILIO_ACCOUNT_SID.value: {
        'type': str,
        'help': 'Twilio account SID'
    },
    Argument.TWILIO_AUTH_TOKEN.value: {
        'type': str,
        'help': 'Twilio auth token'
    },
    Argument.TWILIO_FROM_NUMBER.value: {
        'type': str,
        'help': 'Twilio sms sending phone number'
    },
    Argument.SMS_TO_NUMBER.value: {
        'type': str,
        'help': 'Number to receive sms notifications'
    },
    Argument.TRANSACTIONS_CHECK_INTERVAL.value: {
        'type': int,
        'help': 'How often to check for transactions in seconds',
        'default': 3600  # 1 Hour
    },
    Argument.SMS_TRANSACTION_DATE_FORMAT.value: {
        'type': str,
        'help': 'Datetime format for the transaction date. Refer to https://strftime.org/ for available formatting',
        'default': '%d-%b-%Y %H:%M:%S'
    },
    Argument.LOG_FORMAT.value: {
        'type': str,
        'help': 'Format of the logs. Refer to https://docs.python.org/3/library/logging.html#logrecord-attributes for available formatting',
        'default': '[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s'
    },
    Argument.SMS_ENABLE.value: {
        'type': str,
        'help': 'To enable sms sending',
        'choices': ['yes', 'no'],
        'default': 'no'
    },
    Argument.WEBHOOK_ENABLE.value: {
        'type': str,
        'help': 'To enable webhook sending',
        'choices': ['yes', 'no'],
        'default': 'no'
    },
    Argument.VIBER_BOT_ENABLE.value: {
        'type': str,
        'help': 'To enable viber-bot sending',
        'choices': ['yes', 'no'],
        'default': 'no'
    },
    Argument.WEBHOOK_URL.value: {
        'type': str,
        'help': 'URL for sending the webhook',
        'default': 'http://localhost:5555'
    },
    Argument.WEBHOOK_SECRET_KEY.value: {
        'type': str,
        'help': 'Secret key, generated by you. Used to hash the content and make secure way to check the validity of the webhook at the receiver side.'
    },
    Argument.WEBHOOK_TRANSACTION_DATE_FORMAT.value: {
        'type': str,
        'help': 'Datetime format for the transaction date. Refer to https://strftime.org/ for available formatting',
        'default': '%d-%b-%Y %H:%M:%S'
    },
    Argument.VERSION.value: {
        'action': 'version',
        'version': '1.0'
    },
    Argument.VIBER_BOT_NAME.value: {
        'type': str,
        'help': 'Optional name of the bot. The name is visualized, when you open the bot chat',
        'default': 'Staking Notification'
    },
    Argument.VIBER_BOT_AVATAR.value: {
        'type': str,
        'help': 'Optional picture of the bot. The picture is visualized, when you open the bot chat',
        'default': 'https://hydradex.org/static/media/hydra-logo.92fbca59.png'
    },
    Argument.VIBER_BOT_TOKEN.value: {
        'type': str,
        'help': 'The unique token given after bot creation at the Viber website'
    },
    Argument.VIBER_USER.value: {
        'type': str,
        'help': 'The unique viber user id, which will receive the staking notification messages'
    },
    Argument.VIBER_BOT_TRANSACTION_DATE_FORMAT.value: {
        'type': str,
        'help': 'Datetime format for the transaction date. Refer to https://strftime.org/ for available formatting',
        'default': '%d-%b-%Y %H:%M:%S'
    },
}


class ArgumentParser:

    def __init__(self, application_version):
        parser = argparse.ArgumentParser(description='Hydrachain Staking Notification',
                                         formatter_class=argparse.ArgumentDefaultsHelpFormatter)

        arguments[Argument.VERSION.value]['version'] = application_version

        for arg_name, arg_attrs in arguments.items():
            parser.add_argument(f'--{arg_name}', dest=arg_name, **arg_attrs)

        self.parser = parser
        self.arguments = self.parser.parse_args()

        self._validate_enable_argument_parameters_provided(Argument.SMS_ENABLE,
                                                           [
                                                               Argument.TWILIO_ACCOUNT_SID,
                                                               Argument.TWILIO_AUTH_TOKEN,
                                                               Argument.TWILIO_FROM_NUMBER,
                                                               Argument.SMS_TO_NUMBER
                                                           ])

        self._validate_enable_argument_parameters_provided(Argument.WEBHOOK_ENABLE,
                                                           [
                                                               Argument.WEBHOOK_SECRET_KEY
                                                           ])

        self._validate_enable_argument_parameters_provided(Argument.VIBER_BOT_ENABLE,
                                                           [
                                                               Argument.VIBER_BOT_TOKEN,
                                                               Argument.VIBER_USER
                                                           ])

    def get(self, argument):
        return self.arguments.__getattribute__(argument.value)

    def get_all(self):
        return self.arguments.__dict__

    def _validate_enable_argument_parameters_provided(self, enable_argument, required_arguments):

        if self.get(enable_argument) == 'no':
            return

        self._validate_arguments_present(enable_argument, required_arguments)

        pass

    def _validate_arguments_present(self, argument, required_arguments):
        missing_required_arguments = self.get_arguments_with_none_value(required_arguments)
        missing_required_arguments_with_prefix = self.prefix_arguments('--', missing_required_arguments)

        if len(missing_required_arguments_with_prefix) > 0:
            error_message = f"Argument --{argument.value} requires additional arguments: {', '.join(missing_required_arguments_with_prefix)}"
            self.parser.error(error_message)

    def get_arguments(self):
        return self.arguments

    def check_not_none_values(*values):
        return all(value is not None for value in values)

    def get_arguments_with_none_value(self, arguments):
        arguments_with_none_value = []

        for argument in arguments:
            argument_value = self.get(argument)
            arguments_with_none_value.append(argument) if argument_value == None else None

        return arguments_with_none_value

    def prefix_arguments(self, prefix, arguments):
        return [prefix + a.value for a in arguments]
